#CHOOSE A BASE IMAGE FOR A NODE.JS APPLICATION
FROM

#SET A WORK DIRECTORY e.g. /app
WORKDIR 


#THIS SEEMS GOOD... IT COPIES ALL THE FILES FROM THE CURRENT DIRETORY IN CONTAINER ENVIRONMENT
COPY . .

#RUN COMMANDS NEEDED FOR INSTALLATION OF ALL MODULES LISTED ON package.json FILE AND THEIR DEPENDENCIES
RUN 

#EXPOSE THE PORT DEFAULT PORT FOR node.js APPLICATION
EXPOSE 

#SET ENTRYPOINT FOR A STARTING CONTAINER, HERE. THIS LOOKS GOOD
ENTRYPOINT ["node", "src/index.js"]